routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'HomeController@index')->name('home');
Route::post('/wish', 'HomeController@wish');

Route::group(["prefix" => "dashboard"], function(){
    Route::get('/', 'DashboardController@index');
    Route::resource('bridegrooms', 'BridegroomsController');        
    Route::get('/create_gallery', 'BridegroomsController@create_gallery');    
    Route::post('/gallery', 'BridegroomsController@gallery');    
    Route::get('/bridegroom_images_delete/{id}', 'BridegroomsController@bridegroom_images_delete');
    
    Route::get('/create_wish', 'BridegroomsController@create_wish');    
    Route::post('/wish', 'BridegroomsController@wish');
    Route::get('/bridegroom_wish_delete/{id}', 'BridegroomsController@bridegroom_wish_delete');

    // post
    Route::resource('posts', 'PostController');
    Route::get('/posts/delete/{id}', 'PostController@destroy');

    // users controller
    Route::resource('users', 'UsersController');
    Route::get('/users/delete/{id}', 'UsersController@destroy');

    // user_types controller
    Route::resource('/user_types', 'UserTypesController');
    Route::get('/user_types/delete/{id}', 'UserTypesController@destroy');
});

//static page
Route::get('/cerita/{slug}', 'HomeController@invitation');

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'created_by');
    }
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Auth;
use Hash;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {                
        return view('admins/dashboard');
    }

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Post;

use File;
use Illuminate\Support\Str;
use Carbon\Carbon;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();
        return view("dashboard.posts.index",compact(["posts"]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("dashboard.posts.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $random = Str::random(5);
        
        $post = new Post;                
        $post->title = $input['title'];                     
        $post->body = $input['body'];                     
        $post->created_by = $input['created_by'];                     
        if(isset($input['image'])){
            $files = $input['image'];
            if ($files) {
                $destinationPath    = 'uploads/attachment/posts/'; // The destination were you store the document.
                if(!(file_exists(public_path('/uploads/attachment/posts/'))))
                {
                    File::makeDirectory($destinationPath, $mode = 0777, true, true);
                }
                $filename           = $files->getClientOriginalName(); // Original file name that the end user used for it.
                $mime_type          = $files->getMimeType(); // Gets this example image/png
                $extension          = $files->getClientOriginalExtension(); // The original extension that the user used example .jpg or .png.
                $filename           = time().'-'.$filename; // random file name to replace original
                $upload_success     = $files->move($destinationPath, $filename); // Now we move the file to its new home.
                $post->image = $destinationPath.'/'.$filename;
            }
        }       
        $post->post_date = date("Y-m-d", strtotime($input['post_date']));        
        $post->slug = Str::slug($input['title'].'-'.$random, '-');
        
        $post->save();
        \Session::flash('success','Data Post berhasil dibuat');
        return redirect("dashboard/posts/");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);
        return view("dashboard.posts.show",compact(["post"]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);
        return view("dashboard.posts.edit",compact(["post"]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        //dd($input);
        $post = Post::find($id);           
        $post->title = $input['title'];                     
        $post->body = $input['body'];   
        $post->updated_by = $input['updated_by'];
        if(isset($input['image'])){
            $files = $input['image'];
            if ($files) {
                $destinationPath    = 'uploads/attachment/posts/'; // The destination were you store the document.
                if(!(file_exists(public_path('/uploads/attachment/posts/'))))
                {
                    File::makeDirectory($destinationPath, $mode = 0777, true, true);
                }
                $filename           = $files->getClientOriginalName(); // Original file name that the end user used for it.
                $mime_type          = $files->getMimeType(); // Gets this example image/png
                $extension          = $files->getClientOriginalExtension(); // The original extension that the user used example .jpg or .png.
                $filename           = time().'-'.$filename; // random file name to replace original
                $upload_success     = $files->move($destinationPath, $filename); // Now we move the file to its new home.
                $post->image = $destinationPath.'/'.$filename;
            }
        }       
        $post->post_date = date("Y-m-d", strtotime($input['post_date']));
        $post->status_id = $input['status_id'];
        
        $post->save();
        \Session::flash('success','Data Post berhasil dibuat');
        return redirect("dashboard/posts/");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id);
        if(isset($post->image)){
            // remove image
            unlink($post->image);
        }
        $post->delete();
        \Session::flash('success','Post berhasil dihapus');
        return redirect("dashboard/posts/");
    }
}

resources/views/dashboard/posts/create.blade.php
@extends('layouts.dashboard')

@section('content')
<!-- Basic Form Elements -->
<section class="panel">
    <div class="panel-heading">
        <h3>Form Data Post</h3>
    </div>
    <br />
    <form class="form-horizontal" role="form" method="POST" action="{{ url('/dashboard/posts') }}" enctype="multipart/form-data">
    <div class="panel-body">
        <div class="row">        
            <div class="col-lg-12">
                <div class="margin-bottom-50">                    
                    <br />
                    <!-- Horizontal Form -->                                           
                    <input type="hidden" class="form-control" name="created_by" id="created_by" value="{{ Auth::user()->id }}">
                    @csrf
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">Judul Post</label>
                        </div>
                        <div class="col-md-10">
                            <input id="title" type="text" class="form-control" name="title"  placeholder="Input Judul" autofocus>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">Gambar Post</label>
                        </div>
                        <div class="col-md-10">
                            <input id="image" type="file" class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}" name="image" data-max-size="2097152"  placeholder="Input Gambar Sidang" autofocus>

                            @if ($errors->has('image'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('image') }}</strong>
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">Body</label>
                        </div>
                        <div class="col-md-10">
                            <textarea class="form-control summernote" id="body" name="body" placeholder="Input Isi Post" rows="3" id="l15"></textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">Tanggal Post</label>
                        </div>
                        <div class="col-md-10">
                            <div class="form-group">
                                    <label class="input-group datepicker-only-init">
                                        <input type="text" id="post_date"  class="form-control datepicker-only-init" name="post_date" placeholder="Tanggal Post" autofocus/>
                                        <span class="input-group-addon">
                                            <i class="icmn-calendar"></i>
                                        </span>
                                    </label>
                                </div>
                        </div>
                    </div>  
                    
                    <div class="form-group row">
                            <div class="col-md-2">
                                <label class="form-control-label" for="l0">Status Post</label>
                            </div>
                            <div class="col-md-10">
                                <select id="status_id" type="text" class="selectpicker form-control{{ $errors->has('status_id') ? ' is-invalid' : '' }}" name="status_id"  placeholder="Input status_id" data-live-search="true" required autofocus>
                                    <option>Pilih Status Post</option>
                                    <option value="1">Active</option>
                                    <option value="0">Draft</option>                                    
                                </select>

                                @if ($errors->has('status_id'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('status_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                                                                                                                     
                </div>
            </div>
        </div>  

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    {{ __('Create') }}
                </button>
                <a class="btn btn-success" href="/dashboard/bridegrooms/">Back</a>
            </div>
        </div>
    </div>
    </form>
    <!-- End Horizontal Form -->      
</section>
<!-- End -->
<script>
    $(function(){
        $('.select2').select2();

        $('.summernote').summernote({
            height: 350
        });

        $('.datepicker-only-init').datetimepicker({
            widgetPositioning: {
                horizontal: 'left'
            },
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-arrow-up",
                down: "fa fa-arrow-down"
            },
            format: 'YYYY-MM-DD'
        });

        var image = $('#image');        
        var maxSize = image.data('max-size');
        var document = $('#document_0');
        $("form").submit(function(){
            if(image.val() != '' && image.get(0).files[0].size>maxSize){
                alert('file gambar sidang melebihi batas ' +maxSize+ ' bytes');
                return false;
            }else if(document.val() != '' && document.get(0).files[0].size>maxSize){
                alert('file dokumen repot melebihi batas ' +maxSize+ ' bytes');
                return false;
            }      
        });
    })
</script>
@endsection

resources/views/dashboard/posts/edit.blade.php
@extends('layouts.dashboard')

@section('content')
<!-- Basic Form Elements -->
<section class="panel">
    <div class="panel-heading">
        <h3>Form Data Post</h3>
    </div>
    <br />
    <form class="form-horizontal" role="form" method="POST" action="{{ route('posts.update', $post->id) }}" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="panel-body">
        <div class="row">        
            <div class="col-lg-12">
                <div class="margin-bottom-50">                    
                    <br />
                    <!-- Horizontal Form -->                                           
                    <input type="hidden" class="form-control" name="updated_by" id="updated_by" value="{{ Auth::user()->id }}">
                    @csrf
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">Judul Post</label>
                        </div>
                        <div class="col-md-10">
                            <input id="title" type="text" class="form-control" name="title"  placeholder="Input Judul" value="{{$post->title}}" autofocus>
                        </div>
                    </div>                    
                    @if($post->image)
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">Gambar Post</label>
                        </div>
                        <div class="col-md-4">
                            <img id="image" src="/{{$post->image}}" alt="{{$post->image}}" style="width:100%;max-width:300px">                                
                        </div>
                        <div class="col-md-6">
                            <input id="image" type="file" class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}" name="image"  placeholder="Input Gambar Sidang" autofocus>

                            @if ($errors->has('image'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('image') }}</strong>
                                </span>
                            @endif
                        </div>                            
                    </div>
                    <div class="form-group row">
                        <div class="col-xs-2"></div>
                        <div class="col-xs-10">
                            <p class="text-red">* Upload jika ingin merubah gambar post</p>
                            <p class="text-red">* Ukuran Maksimal File 2MB</p>
                            <p class="text-red">* Format File : jpeg, jpg, png</p>
                        </div>
                    </div>                        
                    @else
                    <div class="form-group row">
                        <div class="col-md-4">
                            <label class="form-control-label" for="l0">Gambar Post</label>
                        </div>
                        <div class="col-md-8">
                            <input id="image" type="file" class="form-control{{ $errors->has('image') ? ' is-invalid' : '' }}" name="image"  placeholder="Input Gambar Sidang" autofocus>

                            @if ($errors->has('image'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('image') }}</strong>
                                </span>
                            @endif
                        </div>                            
                    </div>
                    <div class="form-group row">
                        <div class="col-md-4"></div>
                        <div class="col-xs-2">
                            <p class="text-red">* Ukuran Maksimal File 2MB</p>
                            <p class="text-red">* Format File : jpeg, jpg, png</p>
                        </div>
                    </div>
                    @endif
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">Body</label>
                        </div>
                        <div class="col-md-10">
                            <textarea class="form-control summernote" id="body" name="body" placeholder="Input Isi Post" rows="3" id="l15">
                                {{$post->body}}
                            </textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">Tanggal Post</label>
                        </div>
                        <div class="col-md-10">
                            <div class="form-group">
                                    <label class="input-group datepicker-only-init">
                                        <input type="text" id="post_date"  class="form-control datepicker-only-init" name="post_date" value="{{$post->post_date}}" placeholder="Tanggal Post" autofocus/>
                                        <span class="input-group-addon">
                                            <i class="icmn-calendar"></i>
                                        </span>
                                    </label>
                                </div>
                        </div>
                    </div>  
                    
                    <div class="form-group row">
                            <div class="col-md-2">
                                <label class="form-control-label" for="l0">Status Post</label>
                            </div>
                            <div class="col-md-10">
                                <select id="status_id" type="text" class="selectpicker form-control{{ $errors->has('status_id') ? ' is-invalid' : '' }}" name="status_id"  placeholder="Input status_id" data-live-search="true" required autofocus>
                                    <option>Pilih Status Post</option>                                
                                    <option value="1" @if($post->status_id==1) selected @endif >Active</option>
                                    <option value="0" @if($post->status_id==0) selected @endif >Draft</option>                                    
                                </select>

                                @if ($errors->has('status_id'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('status_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                                                                                                                     
                </div>
            </div>
        </div>  

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    {{ __('Create') }}
                </button>
                <a class="btn btn-success" href="/dashboard/post/">Back</a>
            </div>
        </div>
    </div>
    </form>
    <!-- End Horizontal Form -->      
</section>
<!-- End -->
<script>
    $(function(){
        $('.select2').select2();

        $('.summernote').summernote({
            height: 350
        });

        $('.datepicker-only-init').datetimepicker({
            widgetPositioning: {
                horizontal: 'left'
            },
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-arrow-up",
                down: "fa fa-arrow-down"
            },
            format: 'YYYY-MM-DD'
        });

        var image = $('#image');        
        var maxSize = image.data('max-size');
        var document = $('#document_0');
        $("form").submit(function(){
            if(image.val() != '' && image.get(0).files[0].size>maxSize){
                alert('file gambar sidang melebihi batas ' +maxSize+ ' bytes');
                return false;
            }else if(document.val() != '' && document.get(0).files[0].size>maxSize){
                alert('file dokumen repot melebihi batas ' +maxSize+ ' bytes');
                return false;
            }      
        });
    })
</script>
@endsection

resources/views/dashboard/posts/show.blade.php
@extends('layouts.dashboard')

@section('content')
<!-- Basic Form Elements -->
<section class="panel">
    <div class="panel-heading">
        <h3>Form Data Post</h3>
    </div>
    <br />
    <form class="form-horizontal" role="form" method="POST" action="{{ route('posts.update', $post->id) }}" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="panel-body">
        <div class="row">        
            <div class="col-lg-12">
                <div class="margin-bottom-50">                    
                    <br />
                    <!-- Horizontal Form -->                                           
                    <input type="hidden" class="form-control" name="updated_by" id="updated_by" value="{{ Auth::user()->id }}">
                    @csrf
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">Judul Post</label>
                        </div>
                        <div class="col-md-10">
                            <input id="title" type="text" class="form-control" name="title"  placeholder="Input Judul" value="{{$post->title}}" autofocus readonly>
                        </div>
                    </div>                   
                    @if($post->image)
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">Gambar Post</label>
                        </div>
                        <div class="col-md-8">
                            <img id="image" src="/{{$post->image}}" alt="{{$post->image}}" style="width:100%;max-width:300px">                                
                        </div>                          
                    </div>                                          
                    @else                    
                    <div class="form-group row">
                        <div class="col-md-4"></div>
                        <div class="col-xs-2">
                            <p class="text-red">Gambar post belum di upload</p>
                        </div>
                    </div>
                    @endif
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">Body</label>
                        </div>
                        <div class="col-md-10">
                            <p>
                                {!!$post->body!!}
                            </p>                                
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-2">
                            <label class="form-control-label" for="l0">Tanggal Post</label>
                        </div>
                        <div class="col-md-10">
                            <div class="form-group">
                                    <label class="input-group datepicker-only-init">
                                        <input type="text" id="post_date"  class="form-control datepicker-only-init" name="post_date" value="{{$post->post_date}}" placeholder="Tanggal Post" autofocus readonly/>
                                        <span class="input-group-addon">
                                            <i class="icmn-calendar"></i>
                                        </span>
                                    </label>
                                </div>
                        </div>
                    </div>  
                    
                    <div class="form-group row">
                            <div class="col-md-2">
                                <label class="form-control-label" for="l0">Status Post</label>
                            </div>
                            <div class="col-md-10">
                                @if($post->status_id==1) 
                                    <p>
                                    Active
                                    </p>                                    
                                @else 
                                    <p>
                                    Draft
                                    </p>                                    
                                @endif                                
                            </div>
                        </div>
                                                                                                                     
                </div>
            </div>
        </div>  

        <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <a class='btn btn-info' href='{{url('dashboard/posts/'.$post->id.'/edit')}}'>Edit</a>
                <a class="btn btn-success" href="/dashboard/post/">Back</a>
            </div>
        </div>
    </div>
    </form>
    <!-- End Horizontal Form -->      
</section>
<!-- End -->
<script>
    $(function(){
        $('.select2').select2();

        $('.summernote').summernote({
            height: 350
        });

        $('.datepicker-only-init').datetimepicker({
            widgetPositioning: {
                horizontal: 'left'
            },
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-arrow-up",
                down: "fa fa-arrow-down"
            },
            format: 'YYYY-MM-DD'
        });

        var image = $('#image');        
        var maxSize = image.data('max-size');
        var document = $('#document_0');
        $("form").submit(function(){
            if(image.val() != '' && image.get(0).files[0].size>maxSize){
                alert('file gambar sidang melebihi batas ' +maxSize+ ' bytes');
                return false;
            }else if(document.val() != '' && document.get(0).files[0].size>maxSize){
                alert('file dokumen repot melebihi batas ' +maxSize+ ' bytes');
                return false;
            }      
        });
    })
</script>
@endsection