routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'HomeController@index')->name('home');
Route::post('/wish', 'HomeController@wish');

Route::group(["prefix" => "dashboard"], function(){
    Route::get('/', 'DashboardController@index');
    Route::resource('bridegrooms', 'BridegroomsController');        
    Route::get('/create_gallery', 'BridegroomsController@create_gallery');    
    Route::post('/gallery', 'BridegroomsController@gallery');    
    Route::get('/bridegroom_images_delete/{id}', 'BridegroomsController@bridegroom_images_delete');
    
    Route::get('/create_wish', 'BridegroomsController@create_wish');    
    Route::post('/wish', 'BridegroomsController@wish');
    Route::get('/bridegroom_wish_delete/{id}', 'BridegroomsController@bridegroom_wish_delete');

    // post
    Route::resource('posts', 'PostController');
    Route::get('/posts/delete/{id}', 'PostController@destroy');

    // users controller
    Route::resource('users', 'UsersController');
    Route::get('/users/delete/{id}', 'UsersController@destroy');

    // user_types controller
    Route::resource('/user_types', 'UserTypesController');
    Route::get('/user_types/delete/{id}', 'UserTypesController@destroy');
});

//static page
Route::get('/cerita/{slug}', 'HomeController@invitation');

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Auth;
use Hash;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {                
        return view('admins/dashboard');
    }

}

app/Http/Controllers/UserTypesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\UserType;

class UserTypesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user_types = UserType::all();
        return view("dashboard.user_types.index",compact(["user_types"]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("dashboard.user_types.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        
        $user = new UserType;                
        $user->name = $input['name'];                                
        $user->save();
        \Session::flash('success','Data User Type berhasil dibuat');
        return redirect("/dashboard/user_types/");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user_type = UserType::find($id);
        return view("dashboard.user_types.edit",compact(["user_type"]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $user = UserType::find($id);
        $user->name = $input['name'];                                
        $user->save();
        \Session::flash('success','Data User Type berhasil dibuat');
        return redirect("/dashboard/user_types/");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = UserType::find($id);
        $user->delete();
        \Session::flash('success','User Type berhasil di dalete');

        return redirect("/dashboard/user_types/");
    }
}

resources/views/dashboard/user_types/create.blade.php
@extends('layouts.dashboard')

@section('content')
<!-- Basic Form Elements -->
<section class="panel">
    <div class="panel-heading">
        <h3>Tambah User</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="margin-bottom-50">
                    <h4>Form User</h4>
                    <br />
                    <!-- Horizontal Form -->                    
                    <form class="form-horizontal" role="form" method="POST" action="{{ url('/dashboard/user_types') }}" enctype="multipart/form-data">
                         @csrf
                         <input type="hidden" class="form-control" name="created_by" id="created_by" value="{{ Auth::user()->id }}">
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Nama</label>
                            </div>
                            <div class="col-md-9">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name"  placeholder="Input Name" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>                                                       
                         <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Create') }}
                                </button>
                                <a class="btn btn-success" href="/dashboard/user_types">Back</a>
                            </div>
                        </div>
                    </form>
                    <!-- End Horizontal Form -->
                </div>
            </div>
        </div>        
</section>
<!-- End -->
@endsection

resources/views/dashboard/user_types/edit.blade.php
@extends('layouts.dashboard')

@section('content')
<!-- Basic Form Elements -->
<section class="panel">
    <div class="panel-heading">
        <h3>Edit Data Tipe User</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="margin-bottom-50">
                    <h4>Form Tipe User</h4>
                    <br />
                    <!-- Horizontal Form -->                    
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('user_types.update', $user_type->id) }}" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                        <input type="hidden" name="id" value="{{ $user_type->id }}">
                        <input type="hidden" class="form-control" name="updated_by" id="updated_by" value="{{ Auth::user()->id }}">
                        <div class="form-group row">
                            <div class="col-md-3">
                                <label class="form-control-label" for="l0">Nama User</label>
                            </div>
                            <div class="col-md-9">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name"  placeholder="Input Name" value="{{ $user_type->name }}" required autofocus>
                                <input type="hidden" class="form-control" name="created_by" id="updated_by" value="{{ Auth::user()->id }}">

                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>                                                             
                         <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Update') }}
                                </button>
                                <a class="btn btn-success" href="/dashboard/user_types">Back</a>
                            </div>
                        </div>
                    </form>
                    <!-- End Horizontal Form -->
                </div>
            </div>
        </div>        
</section>
<!-- End -->
@endsection

resources/views/dashboard/user_types/index.blade.php
@extends('layouts.dashboard')

@section('content')
<section class="page-content">
<div class="page-content-inner">    
    <!--  -->
    <section class="panel">
        <div class="panel-heading">
            <h3>
            Mengelola Tipe Pengguna
            </h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-12">
                    @if ($message = Session::get('success'))
                    <div class="alert alert-success" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>{{ $message }}</strong>
                    </div>
                    @endif
                    <div class="col-md-4">
                        <a href="/dashboard/user_types/create" class="btn btn-primary">
                            Tambah User
                        </a>
                    </div>
                    
                    <div class="col-xs-12">&nbsp;</div>                    
                    <div class="margin-bottom-50">
                        <table class="table table-hover nowrap" id="example1" width="100%">
                            <thead>
                              <tr>
                                <th>Nama</th>
                                <th width="15%">Aksi</th>
                              </tr>
                            <tbody>
                                @foreach($user_types as $user_type)
                                <tr>
                                    <td>{{$user_type->name}}</td>
                                    <td> 
                                        <a class='btn btn-primary btn-xs' href='{{url('/dashboard/user_types/'.$user_type->id.'/edit')}}'>Edit</a>
                                        <a class='btn btn-danger btn-xs open-confirm-hapus' onclick="return confirm('Anda Yakin Hapus Data Ini?')" href='{{url('/dashboard/user_types/delete')}}/{{$user_type->id}}'>Delete</a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End  -->

</div>

<!-- Page Scripts -->
<script>
    $(function(){
        $('.datepicker').datetimepicker({
            format:  "YYYY-MM-DD"
        });
    });
</script>
<!-- End Page Scripts -->
</section>
@endsection